[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.20.0"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Ensure devDependencies are installed for TypeScript
  CI = "false"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Allow iframe embedding for 5GLabX platform
[[headers]]
  for = "/5glabx/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin configuration for static export
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.8
    best-practices = 0.8
    seo = 0.8

# Static files are served directly by Netlify from the publish directory

# Serve 5GLabX platform from public directory
[[redirects]]
  from = "/5glabx"
  to = "/5glabx/"
  status = 200
  force = true

[[redirects]]
  from = "/5glabx/*"
  to = "/5glabx/:splat"
  status = 200
  force = true

# API proxy for 5GLabX backend
[[redirects]]
  from = "/api/5glabx/*"
  to = "https://your-5glabx-backend.example.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}