[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"
  NODE_ENV = "production"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=86400"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions
[functions]
  directory = "netlify/functions"

# Edge functions
[[edge_functions]]
  function = "auth"
  path = "/api/auth/*"

[[edge_functions]]
  function = "webhook"
  path = "/api/webhook/*"

# Form handling
[[forms]]
  name = "contact"
  action = "/api/contact"
  method = "POST"

# Environment variables
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api.5glabx.com"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"

[context.staging.environment]
  NEXT_PUBLIC_API_URL = "https://staging-api.5glabx.com"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-staging-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-staging-anon-key"

# Branch deploys
[context.deploy-preview]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Split testing
[[split_tests]]
  name = "homepage-variant"
  path = "/"
  weight = 0.1

# Analytics
[analytics]
  enabled = true

# Security
[security]
  [security.headers]
    [security.headers.for]
      [security.headers.for."/*"]
        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains"
        Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.5glabx.com https://*.supabase.co;"